# NEED TO DO HEALTH CHECK ON DATABASE TO ENSURE IT IS RUNNING.
# MAY BE HELPFUL TO DO FOR EACH CONTAINER AS WELL

version: "3.9"
services:
  app:
    build: crud-test-app
    ports:
      - "3000:3000"
    depends_on:
      - "server"

  server:
    build: crud-test-server
    ports:
      - "3003:3003"
    depends_on:
      - "database"

  database:
    image: postgres:latest
    ports:
      - "${PG_PORT}:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - ./db:/var/lib/db
